// TRATAMENTO DE ERROS
#define SUCCESS 0
#define ERRO_NO_TIPO_INTEIRO -1
#define ERRO_NO_TAMANHO_STRING -2
#define ERRO_NOME_CAMPO -3
#define ERRO_NOME_TABELA -4
#define ERRO_DE_PARAMETRO -5
#define ERRO_ABRIR_ARQUIVO -6
#define ERRO_VAZIO -7
#define ERRO_IMPRESSAO -8
#define ERRO_LEITURA_DADOS -9
#define ERRO_BUFFER_CHEIO -10
#define ERRO_ABRIR_DICIONARIO -11
#define ERRO_NO_TIPO_CHAR -12
#define ERRO_NO_TIPO_DOUBLE -13
#define ERRO_CAMPO_JA_EXISTENTE -14 //adicionado
#define ERRO_NAO_HA_ESPACO -15 //adicionado
#define ERRO_O_VALOR_NAO_PODE_SER_INSERIDO -16 //adicionado
#define ERRO_A_FK_NAO_REFERENCIA_UMA_TABELA_OU_CHAVE_VALIDA -17 //adicionado
#define ERRO_CAMPO_NAO_EXISTE -18 //adicionado
#define ERRO_TABELA_LIGADA -19 //adicionado
#define ERRO_DE_ALOCACAO NULL
#define ERRO_ABRIR_ESQUEMA NULL
#define ERRO_NOME_TABELA_INVALIDO NULL
#define ERRO_ESTRUTURA_TABELA_NULA NULL
#define ERRO_INSERIR_VALOR NULL
#define ERRO_PAGINA_INVALIDA NULL
#define ERRO_DE_LEITURA NULL
#define ERRO_PARAMETRO NULL
